package api

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/WavexSoftware/OpenCloud/service_ledger"
)

// gatewayDir returns the path to the gateway configuration directory
// (~/.opencloud/gateway/).
func gatewayDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to get home directory: %w", err)
	}
	return filepath.Join(home, ".opencloud", "gateway"), nil
}

// reloadNginx attempts to reload nginx using multiple strategies, since the
// process may or may not be running with sudo.
func reloadNginx() error {
	cmds := [][]string{
		{"nginx", "-s", "reload"},
		{"sudo", "nginx", "-s", "reload"},
		{"sudo", "systemctl", "reload", "nginx"},
	}
	var lastErr error
	for _, args := range cmds {
		cmd := exec.Command(args[0], args[1:]...) //nolint:gosec
		if err := cmd.Run(); err != nil {
			lastErr = err
			continue
		}
		return nil
	}
	return fmt.Errorf("failed to reload nginx: %w", lastErr)
}

// applyGatewayNginxConfig regenerates the nginx gateway include file based on
// the current routes in the service ledger and then reloads nginx.
//
// The generated file is written to ~/.opencloud/gateway/nginx-gateway.conf.
// Each route produces two nginx location blocks:
//  1. An exact-match redirect block so that /prefix redirects to /prefix/.
//  2. A proxy_pass block for /prefix/ that forwards to the target URL.
func applyGatewayNginxConfig(routes map[string]service_ledger.GatewayRouteEntry) error {
	dir, err := gatewayDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create gateway directory: %w", err)
	}

	confPath := filepath.Join(dir, "nginx-gateway.conf")

	var sb strings.Builder
	sb.WriteString("# Auto-generated by OpenCloud Gateway service — do not edit manually.\n\n")

	for _, route := range routes {
		prefix := route.PathPrefix
		// Ensure the prefix starts with a slash.
		if !strings.HasPrefix(prefix, "/") {
			prefix = "/" + prefix
		}

		// Exact-match redirect: /prefix → /prefix/ (improves UX and avoids double-slash)
		withSlash := strings.TrimRight(prefix, "/") + "/"
		fmt.Fprintf(&sb, "location = %s {\n    return 301 %s;\n}\n\n", strings.TrimRight(prefix, "/"), withSlash)

		// Proxy block for /prefix/ → target
		fmt.Fprintf(&sb, "location %s {\n", withSlash)
		fmt.Fprintf(&sb, "    proxy_pass %s;\n", route.TargetURL)
		sb.WriteString("    proxy_http_version 1.1;\n")
		sb.WriteString("    proxy_set_header Upgrade $http_upgrade;\n")
		sb.WriteString("    proxy_set_header Connection 'upgrade';\n")
		sb.WriteString("    proxy_set_header Host $host;\n")
		sb.WriteString("    proxy_set_header X-Real-IP $remote_addr;\n")
		sb.WriteString("    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
		sb.WriteString("    proxy_set_header X-Forwarded-Proto $scheme;\n")
		sb.WriteString("    proxy_cache_bypass $http_upgrade;\n")
		sb.WriteString("}\n\n")
	}

	if err := os.WriteFile(confPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write gateway nginx config: %w", err)
	}

	// Best-effort nginx reload — log failure but do not abort.
	if err := reloadNginx(); err != nil {
		fmt.Fprintf(os.Stderr, "gateway: nginx reload warning: %v\n", err)
	}

	return nil
}

// ListGatewayRoutes handles GET /list-gateway-routes.
// It returns all configured gateway routes as a JSON array.
func ListGatewayRoutes(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	routes, err := service_ledger.GetAllGatewayRouteEntries()
	if err != nil {
		http.Error(w, "Failed to read gateway routes: "+err.Error(), http.StatusInternalServerError)
		return
	}

	// Convert the map to a slice for consistent JSON output.
	list := make([]service_ledger.GatewayRouteEntry, 0, len(routes))
	for _, route := range routes {
		list = append(list, route)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(list)
}

// CreateGatewayRouteRequest is the request body for POST /create-gateway-route.
type CreateGatewayRouteRequest struct {
	PathPrefix  string `json:"pathPrefix"`
	TargetURL   string `json:"targetURL"`
	Description string `json:"description,omitempty"`
}

// CreateGatewayRoute handles POST /create-gateway-route.
// It validates the request, persists the new route in the service ledger, and
// regenerates the nginx gateway config.
func CreateGatewayRoute(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req CreateGatewayRouteRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid JSON", http.StatusBadRequest)
		return
	}

	if req.PathPrefix == "" || req.TargetURL == "" {
		http.Error(w, "Missing required fields: pathPrefix and targetURL", http.StatusBadRequest)
		return
	}

	// Validate that PathPrefix starts with a slash.
	if !strings.HasPrefix(req.PathPrefix, "/") {
		http.Error(w, "pathPrefix must start with '/'", http.StatusBadRequest)
		return
	}

	// Validate TargetURL is a valid URL.
	if _, err := url.ParseRequestURI(req.TargetURL); err != nil {
		http.Error(w, "targetURL is not a valid URL", http.StatusBadRequest)
		return
	}

	// Generate a unique ID.
	b := make([]byte, 8)
	if _, err := rand.Read(b); err != nil {
		http.Error(w, "Failed to generate route ID", http.StatusInternalServerError)
		return
	}
	routeID := hex.EncodeToString(b)

	route := service_ledger.GatewayRouteEntry{
		ID:          routeID,
		PathPrefix:  req.PathPrefix,
		TargetURL:   req.TargetURL,
		Description: req.Description,
		CreatedAt:   time.Now().UTC().Format(time.RFC3339),
	}

	if err := service_ledger.UpsertGatewayRouteEntry(route); err != nil {
		http.Error(w, "Failed to save gateway route: "+err.Error(), http.StatusInternalServerError)
		return
	}

	// Regenerate nginx config.
	routes, err := service_ledger.GetAllGatewayRouteEntries()
	if err == nil {
		_ = applyGatewayNginxConfig(routes)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(route)
}

// UpdateGatewayRouteRequest is the request body for PUT /update-gateway-route/{id}.
type UpdateGatewayRouteRequest struct {
	PathPrefix  string `json:"pathPrefix"`
	TargetURL   string `json:"targetURL"`
	Description string `json:"description,omitempty"`
}

// UpdateGatewayRoute handles PUT /update-gateway-route/{id}.
// It updates an existing route's path prefix, target URL, and optional
// description, then regenerates the nginx config.
func UpdateGatewayRoute(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPut {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Extract the route ID from the URL path: /update-gateway-route/{id}
	routeID := strings.TrimPrefix(r.URL.Path, "/update-gateway-route/")
	if routeID == "" {
		http.Error(w, "Missing route ID", http.StatusBadRequest)
		return
	}

	var req UpdateGatewayRouteRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid JSON", http.StatusBadRequest)
		return
	}

	if req.PathPrefix == "" || req.TargetURL == "" {
		http.Error(w, "Missing required fields: pathPrefix and targetURL", http.StatusBadRequest)
		return
	}

	if !strings.HasPrefix(req.PathPrefix, "/") {
		http.Error(w, "pathPrefix must start with '/'", http.StatusBadRequest)
		return
	}

	if _, err := url.ParseRequestURI(req.TargetURL); err != nil {
		http.Error(w, "targetURL is not a valid URL", http.StatusBadRequest)
		return
	}

	// Fetch existing routes to verify the ID exists.
	existing, err := service_ledger.GetAllGatewayRouteEntries()
	if err != nil {
		http.Error(w, "Failed to read gateway routes: "+err.Error(), http.StatusInternalServerError)
		return
	}

	old, found := existing[routeID]
	if !found {
		http.Error(w, "Gateway route not found", http.StatusNotFound)
		return
	}

	updated := service_ledger.GatewayRouteEntry{
		ID:          routeID,
		PathPrefix:  req.PathPrefix,
		TargetURL:   req.TargetURL,
		Description: req.Description,
		CreatedAt:   old.CreatedAt, // Preserve original creation time.
	}

	if err := service_ledger.UpsertGatewayRouteEntry(updated); err != nil {
		http.Error(w, "Failed to update gateway route: "+err.Error(), http.StatusInternalServerError)
		return
	}

	// Regenerate nginx config.
	routes, err := service_ledger.GetAllGatewayRouteEntries()
	if err == nil {
		_ = applyGatewayNginxConfig(routes)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(updated)
}

// DeleteGatewayRoute handles DELETE /delete-gateway-route/{id}.
// It removes the route from the service ledger and regenerates the nginx config.
func DeleteGatewayRoute(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodDelete {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	routeID := strings.TrimPrefix(r.URL.Path, "/delete-gateway-route/")
	if routeID == "" {
		http.Error(w, "Missing route ID", http.StatusBadRequest)
		return
	}

	if err := service_ledger.DeleteGatewayRouteEntry(routeID); err != nil {
		http.Error(w, "Failed to delete gateway route: "+err.Error(), http.StatusInternalServerError)
		return
	}

	// Regenerate nginx config.
	routes, err := service_ledger.GetAllGatewayRouteEntries()
	if err == nil {
		_ = applyGatewayNginxConfig(routes)
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"message": "Gateway route deleted successfully"})
}
